version: '3'
services:
  reverse-proxy:
    build:
      context: './'
      dockerfile: Dockerfile.prod
    container_name: reverse-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy_network
    volumes: 
      - /etc/letsencrypt:/etc/letsencrypt
networks:
  proxy_network:
    external: true

